const mongoose = require('mongoose');

// Define the schema for individual items within an order
const orderItemSchema = new mongoose.Schema({
  productId: { type: String, required: true },
  name: { type: String, required: true },
  price: { type: Number, required: true },
  quantity: { type: Number, required: true, min: 1 },
  imageUrl: { type: String }, // Optional: to store image URL for reference
});

// Define the main Order schema
const orderSchema = new mongoose.Schema({ // Added userId to req.body
  userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  
  items: [orderItemSchema], // Array of products purchased
  
  totalAmount: { type: Number, required: true },
  
  // Link to the payment transaction (using the transactionId generated by your payment initiation)
  paymentTransactionId: { type: String, required: true, unique: true }, 
  
  status: { 
    type: String, 
    enum: ['pending', 'paid', 'shipped', 'delivered', 'cancelled'], 
    default: 'pending' 
  },
  createdAt: { type: Date, default: Date.now },
  updatedAt: { type: Date, default: Date.now },
});

module.exports = mongoose.model('Order', orderSchema);